/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import Constructores.Alumno;
import Constructores.Curso;
import Constructores.Grupo;
import Constructores.Nodo;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import mensajeria.Chat;

/**
 *
 * @author anton
 */
public class frmCursos extends javax.swing.JFrame {
    private List<Nodo<Curso>> listaNodosCursos;
    private List<Nodo<Alumno>> listaNodosAlumnos;
    private List<Nodo<Grupo>> listaNodosGrupos;
    private Chat chat;
    private Map<String, Chat> chatsPorGrupo = new HashMap<>();

    
    
    public frmCursos(Chat chat) {
        initComponents();
        this.chat = chat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn4 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UCV CHAT");

        jPanel1.setForeground(new java.awt.Color(102, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btn4.setText("jButton1");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel1.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 220, 60));

        btn1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btn1.setText("jButton1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 60));

        btn2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btn2.setText("jButton1");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 60));

        btn3.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 16)); // NOI18N
        btn3.setText("jButton1");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 220, 60));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 36)); // NOI18N
        jLabel1.setText("SELECCIONE EL CURSO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Lista de Cursos
    public void setListaNodosCursos(List<Nodo<Curso>> listaNodosCursos) {
        this.listaNodosCursos = listaNodosCursos;
        cambiarTexto();
    }
    
    //Lista de Alumnos
    public void setListaNodosAlumnos(List<Nodo<Alumno>> listaNodosAlumnos) {
        this.listaNodosAlumnos = listaNodosAlumnos;
    }
    
    //Lista de Grupos
    public void setListaNodosGrupos(List<Nodo<Grupo>> listaNodosGrupos) {
        this.listaNodosGrupos = listaNodosGrupos;
    }

    
    private void cambiarTexto() {
        // Verificar si hay suficientes nodos de cursos para actualizar todos los botones
        if (listaNodosCursos.size() >= 4) {
            btn1.setText(listaNodosCursos.get(0).getData().getNombre());
            btn2.setText(listaNodosCursos.get(1).getData().getNombre());
            btn3.setText(listaNodosCursos.get(2).getData().getNombre());
            btn4.setText(listaNodosCursos.get(3).getData().getNombre());
        } else {
            System.out.println("No hay suficientes cursos para actualizar todos los botones.");
        }
    }
    
    private void abrirFrmMensajes(int index) {
        String nombreGrupo = listaNodosCursos.get(index).getData().getNombre();
        
        // Obtener el chat correspondiente al grupo o crear uno nuevo si no existe
        Chat chatGrupo = chatsPorGrupo.getOrDefault(nombreGrupo, new Chat());
        chatsPorGrupo.putIfAbsent(nombreGrupo, chatGrupo);

        // Pasar el chat del grupo correspondiente al nuevo frmMensajes
        frmMensajes mensajes = new frmMensajes(chatGrupo);
        mensajes.setListaNodosCursos(listaNodosCursos);
        mensajes.setListaNodosAlumnos(listaNodosAlumnos);
        mensajes.setGrupo(nombreGrupo);
        mensajes.setVisible(true);
    }
    
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        abrirFrmMensajes(0);
        abrirFrmMensajes(0);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        abrirFrmMensajes(1);
        abrirFrmMensajes(1);
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        abrirFrmMensajes(2);
        abrirFrmMensajes(2);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        abrirFrmMensajes(3);
        abrirFrmMensajes(3);
    }//GEN-LAST:event_btn4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
