/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import java.util.HashMap;
import java.util.Map;
import mensajeria.Chat;
import mensajeria.Mensaje;
import java.util.List;

/**
 *
 * @author anton
 */
public class frmHistorial extends javax.swing.JFrame {
    
    private Chat chat;
    private Map<String, Chat> chatsPorGrupo = new HashMap<>();
    private String nombreCurso;
    
    
    public frmHistorial(Chat chat, String nombreCurso) {
        initComponents();
        this.chat = chat;
        this.nombreCurso = nombreCurso;
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHistorial = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UCV CHAT");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel1.setText("Historial");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ucvxs.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        lblCurso.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblCurso.setText("Curso:");
        jPanel1.add(lblCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 230, -1));

        txtAreaHistorial.setEditable(false);
        txtAreaHistorial.setColumns(20);
        txtAreaHistorial.setRows(5);
        jScrollPane1.setViewportView(txtAreaHistorial);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 300));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void iniciar(){
        lblCurso.setText("Curso : " + nombreCurso);
        mostrarHistorial();
    }

    private void mostrarHistorial() {
        List<Mensaje> mensajes = chat.getMensajes();
        txtAreaHistorial.setText("");
        for (Mensaje mensaje : mensajes) {
            txtAreaHistorial.append(mensaje.toString() + "\n");
        }
    }
    private void abrirFrmMensajes(int index) {
//        String nombreGrupo = listaNodosCursos.get(index).getData().getNombre();
//        
//        // Obtener el chat correspondiente al grupo o crear uno nuevo si no existe
//        Chat chatGrupo = chatsPorGrupo.getOrDefault(nombreGrupo, new Chat());
//        chatsPorGrupo.putIfAbsent(nombreGrupo, chatGrupo);
//
//        // Pasar el chat del grupo correspondiente al nuevo frmMensajes
//        frmMensajes mensajes = new frmMensajes(chatGrupo);
//        mensajes.setListaNodosCursos(listaNodosCursos);
//        mensajes.setListaNodosAlumnos(listaNodosAlumnos);
//        mensajes.setGrupo(nombreGrupo);
//        mensajes.setVisible(true);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JTextArea txtAreaHistorial;
    // End of variables declaration//GEN-END:variables
}
